### ISSUE TITLE
incremental updates from downloaded data, is this possible?

### ISSUE THREAD

**Issue by rkiddy** [california-civic-data-coalition/django-calaccess-raw-data#257] opened 2015-03-27 17:36 UTC
My downloader/chopper-upper does this the same as yours. It downloads the data and re-parses and re-loads everything in the entire database every time.

Have you all scoped out how to do incremental loads? In other words, if I downloaded and set up the data yesterday and I fetch again today, it would be nice if it could just add the several hundred new rows instead of starting from scratch and processing millions of rows.

It really seems that this should be possible. After all, the SoS does not correct any data. So, once something is added, it should not be going away. It would be good to be able to take advantage of this and make daily update quicker.

**Comment by aboutaaron** [comment] 2015-03-31 17:56
This would be very smart. I imagine you could fetch the archive and diff the TSVs to see what's changed and only load what's been added.

**Comment by rkiddy** [comment] 2015-03-31 20:07
Yes, I could. (That was a very github answer, btw. :-)

It is not as trivial as it might seem to do this because I correct some of the data before I do the load. For example, there are rows in the TSV where a field value ends with a '\' character, which blows the number of columns and causes the row to be rejected. There are rows where people have put in '\r\ characters in the middle of their data. I correct these and some other things. You all do not do this, yes? I notice that your load skips some rows.

Another thing I do in my files is that I add a pk to the front of the file. You all let django assign an id value but that means that you may not be able to tell exactly which row in the TSV file matches to which row in the table. Am I right about this?

I have scripts which allow me to look at a row in a table and see the data out of the TSV file that created it. This has occasionally been very useful.

There may be a way around the issue. If one keeps the uncorrected data, one can see where the rows changed. One can then do the corrections again and build queries to identify those rows in the table. But I am not sure this would be wholly reliable.

Do you all have any objection to adding a pk to the csv files that you all generate from the tsv files? It is certainly easy to do this. I just use awk. It might also make other things clearer. I think I can generate a pull request for this without too much effort.

**Comment by rkiddy** [comment] 2015-04-08 22:26
I am looking to add code which adds a id number to the import file. The model can be changed so that the primary keys of the tables are not auto-generated. In my scripts, I was taking each TSV file on it and running this:
```
awk '{if (NR=0) print "id\t"$0; else print (NR-1)"\t"$0}'
```
and replacing the TSV file with the output from this. I am seeing several ways to do this in the python code, but none as simple as this command.

As I was doing this, I checked the conversion of the TSV files to the csv files. Is this right? This is with the released django-calaccess-raw-data (ie doing a "pip install") and not with my copy of the code. I am surprised to see that so many lines of data are disappearing. Have I done something wrong here? Do you all see this as well? Why would 2/3 of the expn file, for example, be disappearing?
```
$ find data/tsv data/csv -type f -ls | \
    awk '{print $NF, $7}' | \
    tr '[A-Z]' '[a-z]' | \
    awk 'BEGIN{FS="/"}{print $NF}' | \
    sort | \
    awk 'BEGIN{FS=".";last=""}{if ($1 != last) print ""; print $0; last=$1}'

acronyms_cd.csv 43105
acronyms_cd.tsv 36031

address_cd.csv 19882087
address_cd.tsv 15461937

ballot_measures_cd.csv 18356
ballot_measures_cd.tsv 17028

cvr2_campaign_disclosure_cd.csv 19244800
cvr2_campaign_disclosure_cd.tsv 12164158

cvr2_lobby_disclosure_cd.csv 8069948
cvr2_lobby_disclosure_cd.tsv 5798666

cvr2_registration_cd.csv 7227935
cvr2_registration_cd.tsv 5176021

cvr2_so_cd.csv 6448372
cvr2_so_cd.tsv 4182856

cvr3_verification_info_cd.csv 21227758
cvr3_verification_info_cd.tsv 15724702

cvr_campaign_disclosure_cd.csv 161512513
cvr_campaign_disclosure_cd.tsv 104653574

cvr_e530_cd.csv 54398
cvr_e530_cd.tsv 42174

cvr_f470_cd.csv 0
cvr_f470_cd.tsv 0

cvr_lobby_disclosure_cd.csv 126789418
cvr_lobby_disclosure_cd.tsv 99732892

cvr_registration_cd.csv 21054006
cvr_registration_cd.tsv 15172265

cvr_so_cd.csv 6511823
cvr_so_cd.tsv 5019263

debt_cd.csv 74290444
debt_cd.tsv 48294476

efs_filing_log_cd.csv 10519894
efs_filing_log_cd.tsv 8758126

expn_cd.csv 1266640882
expn_cd.tsv 781034344

f495p2_cd.csv 73652
f495p2_cd.tsv 59348

f501_502_cd.csv 5012499
f501_502_cd.tsv 3392096

f690p2_cd.csv 3493865
f690p2_cd.tsv 3122285

filer_acronyms_cd.csv 32194
filer_acronyms_cd.tsv 25772

filer_address_cd.csv 23081169
filer_address_cd.tsv 19154659

filer_ethics_class_cd.csv 600026
filer_ethics_class_cd.tsv 514436

filer_filings_cd.csv 281257943
filer_filings_cd.tsv 223974551

filer_interests_cd.csv 1744409
filer_interests_cd.tsv 1460665

filer_links_cd.csv 26526393
filer_links_cd.tsv 21905721

filername_cd.csv 125223831
filername_cd.tsv 102389549

filers_cd.csv 3733974
filers_cd.tsv 3055062

filer_status_types_cd.csv 155
filer_status_types_cd.tsv 119

filer_to_filer_type_cd.csv 47498546
filer_to_filer_type_cd.tsv 32473906

filer_type_periods_cd.csv 0
filer_type_periods_cd.tsv 0

filer_types_cd.csv 721
filer_types_cd.tsv 531

filer_xref_cd.csv 19006052
filer_xref_cd.tsv 16290660

filing_period_cd.csv 152223
filing_period_cd.tsv 131937

filings_cd.csv 30712525
filings_cd.tsv 24047745

group_types_cd.csv 418
group_types_cd.tsv 292

hdr_cd.csv 41885133
hdr_cd.tsv 30394095

header_cd.csv 12383
header_cd.tsv 10247

image_links_cd.csv 787521
image_links_cd.tsv 645481

latt_cd.csv 10766866
latt_cd.tsv 8097026

lccm_cd.csv 13810262
lccm_cd.tsv 9750319

legislative_sessions_cd.csv 1058
legislative_sessions_cd.tsv 872

lemp_cd.csv 76567339
lemp_cd.tsv 64707902

lexp_cd.csv 36398903
lexp_cd.tsv 28090980

loan_cd.csv 18908659
loan_cd.tsv 12429061

lobby_amendments_cd.csv 2655914
lobby_amendments_cd.tsv 1825406

lobbying_chg_log_cd.csv 11262119
lobbying_chg_log_cd.tsv 8636795

lobbyist_contributions1_cd.csv 694624
lobbyist_contributions1_cd.tsv 603540

lobbyist_contributions2_cd.csv 694624
lobbyist_contributions2_cd.tsv 603540

lobbyist_contributions3_cd.csv 694624
lobbyist_contributions3_cd.tsv 603540

lobbyist_emp_lobbyist1_cd.csv 130881
lobbyist_emp_lobbyist1_cd.tsv 112851

lobbyist_emp_lobbyist2_cd.csv 130881
lobbyist_emp_lobbyist2_cd.tsv 112851

lobbyist_employer1_cd.csv 288400
lobbyist_employer1_cd.tsv 219160

lobbyist_employer2_cd.csv 288417
lobbyist_employer2_cd.tsv 219177

lobbyist_employer3_cd.csv 288417
lobbyist_employer3_cd.tsv 219177

lobbyist_employer_firms1_cd.csv 32277
lobbyist_employer_firms1_cd.tsv 27021

lobbyist_employer_firms2_cd.csv 32277
lobbyist_employer_firms2_cd.tsv 27021

lobbyist_employer_history_cd.csv 0
lobbyist_employer_history_cd.tsv 0

lobbyist_firm1_cd.csv 36792
lobbyist_firm1_cd.tsv 27538

lobbyist_firm2_cd.csv 36792
lobbyist_firm2_cd.tsv 27538

lobbyist_firm3_cd.csv 36792
lobbyist_firm3_cd.tsv 27538

lobbyist_firm_employer1_cd.csv 36322
lobbyist_firm_employer1_cd.tsv 32560

lobbyist_firm_employer2_cd.csv 36322
lobbyist_firm_employer2_cd.tsv 32560

lobbyist_firm_history_cd.csv 0
lobbyist_firm_history_cd.tsv 0

lobbyist_firm_lobbyist1_cd.csv 45030
lobbyist_firm_lobbyist1_cd.tsv 38086

lobbyist_firm_lobbyist2_cd.csv 45030
lobbyist_firm_lobbyist2_cd.tsv 38086

lookup_codes_cd.csv 39626
lookup_codes_cd.tsv 32840

loth_cd.csv 2344626
loth_cd.tsv 1840906

lpay_cd.csv 87144015
lpay_cd.tsv 65791563

names_cd.csv 36611584
names_cd.tsv 28084227

rcpt_cd.csv 2716141579
rcpt_cd.tsv 1610992531

received_filings_cd.csv 44966644
received_filings_cd.tsv 39711660

reports_cd.csv 3591
reports_cd.tsv 2967

s401_cd.csv 7854277
s401_cd.tsv 4840768

s496_cd.csv 3749247
s496_cd.tsv 2931806

s497_cd.csv 139912920
s497_cd.tsv 93681713

s498_cd.csv 2079151
s498_cd.tsv 1400445

smry_cd.csv 365300812
smry_cd.tsv 229793572

splt_cd.csv 207217987
splt_cd.tsv 158555699

text_memo_cd.csv 221059593
text_memo_cd.tsv 200972246
```

**Comment by palewire** [comment] 2016-01-13 06:28
This is a duplicate of #272

**Closed by palewire** 2016-01-13 06:28 UTC
Labels: backend, enhancement, question
